# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('published_date', models.DateTimeField(verbose_name='date published')),
                ('content', models.CharField(max_length=10000)),
                ('hero_image', models.CharField(max_length=200)),
                ('support_image', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=200)),
            ],
        ),
    ]
